version: "3.5"
services:
  notebooks:
    container_name: dmml-notebooks
    build: 
      context: .
      dockerfile: Dockerfile.notebooks
    command: ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=25708b9f-4733-4d20-93a6-dac3359f5a9b"]
    volumes:
      - ./:/src
    env_file:
      - .env
    environment:
      - PYTHONPATH=/src
    ports:
       - 8888:8888

  mlflow:
    container_name: dmml-mlflow-server
    build: 
      context: .
      dockerfile: Dockerfile.mlflow
    command: ["mlflow", "ui", "--host=0.0.0.0", "--backend-store-uri=file:///mlflow", "--port=5000"]
    volumes:
      - ./assets/mlflow:/mlflow
    ports:
      - 5001:5000
    env_file:
      - .env